import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import argparse
from stable_baselines3 import PPO

import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../src/models')))

from src.envs.core.environment import CoreEnv
from src.envs.wrappers.feature_wrappers import DomainFeatureWrapper
from src.envs.wrappers.action_wrappers import ResidualActionWrapper
from src.agents.heuristic_agent import HeuristicAgent

sns.set_theme(style="whitegrid")
sns.set_context("talk")

def simulate_sc_dynamics(model_path, agent_type, out_dir):
    print(f"Loading {agent_type} from {model_path} for SC Dynamics Simulation...")
    
    base_env = CoreEnv(
        topology='base', 
        demand_type='shock', # Shock is best for seeing the Bullwhip effect
        use_goodwill=False, 
        is_blind=False,
        max_episodes=1, 
        render_mode=None
    )
    
    if agent_type == 'Residual':
        heuristic_base = HeuristicAgent(base_env, is_blind=False)
        env = ResidualRLWrapper(base_env, heuristic_base, is_blind=False)
    else:
        env = DomainFeatureWrapper(base_env, is_blind=False)
        
    try:
        model = PPO.load(model_path)
    except Exception as e:
        print(f"Error loading model: {e}")
        return
        
    num_periods = base_env.num_periods
    num_nodes = len(env.main_nodes)
    
    # Storage
    # We will track exactly what SC professionals care about: Inventory and Order Quantities
    inventory_levels = {node: np.zeros(num_periods) for node in env.main_nodes}
    orders_placed = {node: np.zeros(num_periods) for node in env.main_nodes}
    retail_demand = np.zeros(num_periods)
    
    observation, info = env.reset(seed=42)
    
    step = 0
    done = False
    truncated = False
    
    print("Simulating 1 episode with Demand Shock...")
    while not (done or truncated) and step < num_periods:
        # Record pre-step physical state
        # True demand generated by the environment for this timestep (Retail node faces this)
        if step < num_periods:
            retail_demand[step] = base_env.D[step]
            
        for i, node in enumerate(env.main_nodes):
            node_idx = base_env.network.node_map[node]
            # Actual on-hand inventory
            inventory_levels[node][step] = base_env.X[step, node_idx]
            
        action, _states = model.predict(observation, deterministic=True)
        
        # We need to map the normalized action [-1, 1] back to physical order quantities
        # In this env wrapper, typically action maps to fraction of max_order
        for i, node in enumerate(env.main_nodes):
            # For visualization, we plot the continuous policy signal. 
            # (If we had access to the exact converted un-normalized Q matrix from base_env, we'd use it. 
            # We map it to a rough positive scale for relative order variance comparison).
            
            # Action space is usually Box(-1, 1). Let's map it roughly to 0-100% of max capacity
            # This is sufficient to calculate relative variance for Bullwhip.
            normalized_order_signal = (action[i] + 1) / 2.0 
            orders_placed[node][step] = normalized_order_signal * 100 # arbitrary scale for visualization
            
        observation, reward, done, truncated, info = env.step(action)
        step += 1

    # --- Plot 1: Node-Level Inventory Trajectories ---
    plt.figure(figsize=(14, 8))
    for node in env.main_nodes:
        plt.plot(range(num_periods), inventory_levels[node], label=f'Node {node} (Inventory)', linewidth=2.5)
        
    # Overlay the shock demand to show *why* inventory dips
    plt.plot(range(num_periods), retail_demand * 10, label='Retail Demand (Scaled 10x)', 
             linewidth=2, linestyle='--', color='black', alpha=0.7)
             
    plt.title(f'{agent_type}: Inventory Trajectories during Demand Shock', fontsize=18, pad=20)
    plt.xlabel('Simulation Day (Timestep)', fontsize=14)
    plt.ylabel('Physical Units on Hand', fontsize=14)
    plt.legend(title='Supply Chain Echelon', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, f'SC_INVENTORY_TRAJ_{agent_type}.png'), dpi=300, bbox_inches='tight')
    plt.close()
    
    # --- Plot 2: The Bullwhip Effect (Order Variance) ---
    # Bullwhip is defined as Variance(Orders) / Variance(Demand) moving up the supply chain
    # We will plot the raw order signals over time to visually show amplification
    
    plt.figure(figsize=(14, 8))
    
    # We plot demand and the order signals
    plt.plot(range(num_periods), retail_demand, label='Consumer Demand (Retail Faces)', 
             linewidth=3, color='black')
             
    # Plot order signals for nodes (Nodes higher up the chain like 0, 1)
    colors = sns.color_palette("muted", num_nodes)
    for idx, node in enumerate(env.main_nodes):
        var_ratio = np.var(orders_placed[node]) / np.var(retail_demand) if np.var(retail_demand) > 0 else 0
        plt.plot(range(num_periods), orders_placed[node], 
                 label=f'Node {node} Orders (Var Ratio: {var_ratio:.2f})', 
                 linewidth=2, color=colors[idx])
                 
    plt.title(f'{agent_type}: Order Amplification (Bullwhip Effect Analysis)', fontsize=18, pad=20)
    plt.xlabel('Simulation Day (Timestep)', fontsize=14)
    plt.ylabel('Order Quantity Signal / Demand Units', fontsize=14)
    plt.legend(title='Signal Source', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, f'SC_BULLWHIP_{agent_type}.png'), dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Saved Supply Chain visual diagnostics to {out_dir}/")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--agent', type=str, default='RLGNN', choices=['RLV2', 'RLV3', 'RLV4', 'Residual', 'RLGNN'])
    args = parser.parse_args()
    
    out_dir = "data/logs/charts"
    os.makedirs(out_dir, exist_ok=True)
    
    model_paths = {
        'RLV2': 'data/logs/ppo_v2_logs/best_model.zip',
        'RLV3': 'data/logs/ppo_v3_logs/best_model.zip',
        'RLV4': 'data/logs/ppo_v4_logs/best_model.zip',
        'Residual': 'data/logs/ppo_residual_logs/best_model.zip',
        'RLGNN': 'data/logs/ppo_gnn_logs/best_model.zip'
    }
    
    target_path = model_paths[args.agent]
    if os.path.exists(target_path):
        simulate_sc_dynamics(target_path, args.agent, out_dir)
    else:
        print(f"Error: Model file {target_path} not found.")

if __name__ == "__main__":
    main()
